# Python Lesson 09: Matrices: Definition, Order, Equality, Addition, Scalar Multiple

**Concept page:** `wiki/concepts/matrices.md` · **Area:** linear-algebra

**You will be able to:**
- create matrices and read their order
- add and scale matrices
- use matrices to store data tables

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. A matrix is a table

In [2]:
books=np.array([[13,5,7],[8,10,4]])   # shelves x subjects
print(books, "order:", books.shape)
print("entry a_12 =", books[0,1])

[[13  5  7]
 [ 8 10  4]] order: (2, 3)
entry a_12 = 5


## 2. Equality, addition, scalar multiple

In [3]:
A=np.array([[30,20,25],[35,25,23]]); B=np.array([[35,28,20],[40,21,30]])
print(A+B)              # production over two months
print(2*A)
print(np.array_equal(A,A.copy()), np.array_equal(A,B))

[[65 48 45]
 [75 46 53]]
[[60 40 50]
 [70 50 46]]
True False


## 3. Rows = examples, columns = features (ML view)

In [4]:
import pandas as pd
df=pd.DataFrame(books,index=["shelf 1","shelf 2"],columns=["maths","physics","chemistry"]); print(df); print(df.values.shape)

         maths  physics  chemistry
shelf 1     13        5          7
shelf 2      8       10          4
(2, 3)


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
Grade 11 basic p. 114–118: the bookcase matrix [[13,5,7],[8,10,4]] is 2×3; production tables A=[[30,20,25],[35,25,23]], B=[[35,28,20],[40,21,30]] give A+B=[[65,48,45],[75,46,53]].

In [5]:
print(A+B)

[[65 48 45]
 [75 46 53]]


## Exercises

**Exercise 1.** Check that A+B equals B+A and (A+B)+C equals A+(B+C) for random 3x2 matrices.

In [6]:
# your code here

**Exercise 2.** Build the 3x3 identity with np.eye and show it equals diag(1,1,1).

In [7]:
# your code here

## Solutions
*(Try the exercises first!)*

In [8]:
# Solution 1
rng=np.random.default_rng(0);A,B,C_=[rng.integers(0,9,(3,2)) for _ in range(3)]; assert np.array_equal(A+B,B+A) and np.array_equal((A+B)+C_,A+(B+C_))

In [9]:
# Solution 2
assert np.array_equal(np.eye(3),np.diag([1,1,1]))