# Python Lesson 14: Gaussian Elimination (Row Reduction)

**Concept page:** `wiki/concepts/gaussian-elimination.md` · **Area:** linear-algebra

**You will be able to:**
- implement the three row operations
- reduce a system and back-substitute
- detect redundant/contradictory systems

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. Elementary row operations

In [2]:
def swap(M,i,j): M[[i,j]]=M[[j,i]]
def scale(M,i,k): M[i]*=k
def add_multiple(M,i,j,k): M[j]+=k*M[i]    # row_j += k * row_i

## 2. Solve a 3×3 system step by step

In [3]:
Ab=np.array([[1,1,2,12],[3,-3,-1,3],[2,-1,6,24]],float)
M=Ab.copy()
add_multiple(M,0,1,-3); add_multiple(M,0,2,-2)
print(M)
scale(M,1,1/M[1,1]); add_multiple(M,1,2,-M[2,1]); print(M)
z=M[2,3]/M[2,2]; y=M[1,3]-M[1,2]*z; x=M[0,3]-M[0,1]*y-M[0,2]*z
print("solution:",x,y,z)   # 4, 2, 3

[[  1.   1.   2.  12.]
 [  0.  -6.  -7. -33.]
 [  0.  -3.   2.   0.]]
[[ 1.      1.      2.     12.    ]
 [-0.      1.      1.1667  5.5   ]
 [ 0.      0.      5.5    16.5   ]]
solution: 4.0 2.0000000000000004 3.0


## 3. General routine with partial pivoting

In [4]:
def gauss_solve(A,b):
    n=len(b); M=np.c_[np.array(A,float),np.array(b,float)]
    for i in range(n):
        p=i+np.argmax(abs(M[i:,i])); swap(M,i,p)
        if abs(M[i,i])<1e-12: raise ValueError("singular system")
        scale(M,i,1/M[i,i])
        for j in range(n):
            if j!=i: add_multiple(M,i,j,-M[j,i])
    return M[:,-1]
print(gauss_solve([[2,5],[8,1]],[46,32]))   # 3, 8 (Coursera quiz)

[3. 8.]


In [5]:
try: gauss_solve([[1,1],[2,2]],[10,24])
except ValueError as e: print("caught:",e)

caught: singular system


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
The Grade 9 elimination method (**វិធីបំបាត់**) is exactly step 1–2 above with two unknowns; the book then substitutes back.

In [6]:
print(gauss_solve([[3,1],[2,-3]],[7,12]))   # y=7-3x and 2x-3y=12 -> (3,-2)

[ 3. -2.]


## Exercises

**Exercise 1.** Solve 5a+b=17, 4a-3b=6 with gauss_solve (answer 3, 2).

In [7]:
# your code here

**Exercise 2.** Compare gauss_solve with np.linalg.solve on 5 random 5x5 systems.

In [8]:
# your code here

## Solutions
*(Try the exercises first!)*

In [9]:
# Solution 1
s=gauss_solve([[5,1],[4,-3]],[17,6]); print(s); assert np.allclose(s,[3,2])

[3. 2.]


In [10]:
# Solution 2
rng=np.random.default_rng(0)
for _ in range(5):
    A=rng.normal(size=(5,5));b=rng.normal(size=5); assert np.allclose(gauss_solve(A,b),np.linalg.solve(A,b))