# Python Lesson 15: Row Echelon Form and RREF

**Concept page:** `wiki/concepts/row-echelon-form.md` · **Area:** linear-algebra

**You will be able to:**
- compute REF/RREF with SymPy
- read rank from pivots
- build a mini rref from scratch

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. SymPy's rref

In [2]:
M=sp.Matrix([[1,2,3],[0,1,4],[0,0,1]]); print(M.rref())
M2=sp.Matrix([[5,1],[10,2]]); print(M2.rref(), "rank", M2.rank())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))
(Matrix([
[1, 1/5],
[0,   0]]), (0,)) rank 1


## 2. Own implementation (pivots normalised to 1)

In [3]:
def rref(A,tol=1e-12):
    M=np.array(A,float); r=0; piv=[]
    for c in range(M.shape[1]):
        if r>=M.shape[0]: break
        p=r+np.argmax(abs(M[r:,c]))
        if abs(M[p,c])<tol: continue
        M[[r,p]]=M[[p,r]]; M[r]/=M[r,c]
        for i in range(M.shape[0]):
            if i!=r: M[i]-=M[i,c]*M[r]
        piv.append(c); r+=1
    return M,piv
R,piv=rref([[1,1,1],[1,2,1],[1,1,2]]); print(R,piv)
R,piv=rref([[1,1,1],[2,2,2],[3,3,3]]); print(R,"rank =",len(piv))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0, 1, 2]
[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]] rank = 1


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
Grade 11 style: the Cambodian book solves systems via the inverse/Cramer; RREF gives the same answer without computing an inverse.

In [4]:
print(rref([[2,3,1],[1,-1,2]])[0])

[[ 1.   0.   1.4]
 [-0.   1.  -0.6]]


## Exercises

**Exercise 1.** Row-reduce [[1,2,3],[4,5,6],[7,8,9]] and report the rank.

In [5]:
# your code here

**Exercise 2.** Compare your rref with SymPy on a 3x4 matrix.

In [6]:
# your code here

## Solutions
*(Try the exercises first!)*

In [7]:
# Solution 1
R,piv=rref([[1,2,3],[4,5,6],[7,8,9]]); print(R); assert len(piv)==2

[[ 1.  0. -1.]
 [ 0.  1.  2.]
 [ 0.  0. -0.]]


In [8]:
# Solution 2
A=[[1,2,0,3],[2,4,1,8],[0,0,1,2]]; R,_=rref(A); S=np.array(sp.Matrix(A).rref()[0].tolist(),float); assert np.allclose(R,S)