# Python Lesson 21: Matrix–Vector and Matrix–Matrix Multiplication

**Concept page:** `wiki/concepts/matrix-multiplication.md` · **Area:** linear-algebra

**You will be able to:**
- multiply by hand (row × column) and with @
- check shapes and non-commutativity
- use it for purchases × prices tables

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. Row × column

In [2]:
A=np.array([[2,-1],[0,2]]); B=np.array([[3,1],[1,2]])
print(A@B)          # [[5,0],[2,4]]
print(B@A)          # different: AB != BA

[[5 0]
 [2 4]]
[[ 6 -1]
 [ 2  3]]


## 2. Implement from the definition

In [3]:
def matmul(A,B):
    A,B=np.array(A),np.array(B)
    assert A.shape[1]==B.shape[0], "inner dimensions must match"
    return np.array([[sum(A[i,k]*B[k,j] for k in range(A.shape[1])) for j in range(B.shape[1])] for i in range(A.shape[0])])
print(np.array_equal(matmul(A,B),A@B))

True


## 3. Business example from the Cambodian book

In [4]:
buy=np.array([[18,12,11],[16,20,10]]); price=np.array([[7,6],[4,5],[2,2]])
print(buy@price)      # total cost per buyer per shop
trucks=np.array([[7,2,4],[5,6,3]]); cost=np.array([[900,600],[700,500],[500,400]]); print(trucks@cost)   # [[9700,6800],[10200,7200]]

[[196 190]
 [212 216]]
[[ 9700  6800]
 [10200  7200]]


In [5]:
rng=np.random.default_rng(0); X=rng.normal(size=(5,3)); W=rng.normal(size=(3,2)); print((X@W).shape)   # data x weights

(5, 2)


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
Grade 11 basic p. 123–126: trucks (7,2,4),(5,6,3) × prices [[900,600],[700,500],[500,400]] = [[9700,6800],[10200,7200]].

In [6]:
print(trucks@cost)

[[ 9700  6800]
 [10200  7200]]


## Exercises

**Exercise 1.** Verify associativity (AB)C = A(BC) and distributivity on random 3x3 matrices.

In [7]:
# your code here

**Exercise 2.** Which shapes allow (m x n)(p x q)? Write `can_multiply` and test.

In [8]:
# your code here

## Solutions
*(Try the exercises first!)*

In [9]:
# Solution 1
rng=np.random.default_rng(2);A,B,C_=[rng.normal(size=(3,3)) for _ in range(3)]; assert np.allclose((A@B)@C_,A@(B@C_)) and np.allclose((A+B)@C_,A@C_+B@C_)

In [10]:
# Solution 2
can_multiply=lambda a,b:a[1]==b[0]
assert can_multiply((2,3),(3,2)) and not can_multiply((2,3),(2,3))