# Python Lesson 46: Perceptron and Neural Networks

**Concept page:** `wiki/concepts/perceptron-and-neural-networks.md` · **Area:** ml-connection

**You will be able to:**
- implement a perceptron forward pass with matrices
- train a regression perceptron and a classification perceptron
- see why a single perceptron computes AND but not XOR

*How to use:* run the cells top to bottom, read the output, then try the **Exercises** in the empty cells before opening the **Solutions** section at the bottom.

In [1]:
import numpy as np
import sympy as sp
import matplotlib
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline

## 1. Spam example: score = 1·lottery + 1·win, threshold 1.5

In [2]:
X=np.array([[1,1],[2,1],[0,0],[0,2],[0,1],[1,0],[2,2],[2,0],[1,2]]); y=np.array([1,1,0,1,0,0,1,1,1])
pred=(X@np.array([1,1])-1.5>0).astype(int); print(pred, (pred==y).all())

[1 1 0 1 0 0 1 1 1] True


## 2. Regression perceptron trained by gradient descent

In [3]:
rng=np.random.default_rng(0); x=rng.uniform(0,10,100); t=3*x+5+rng.normal(0,1,100)
w=b=0.
for _ in range(3000):
    yh=w*x+b; w-=0.01*np.mean((yh-t)*x); b-=0.01*np.mean(yh-t)
print(w,b)

2.9875658944420396 4.987996838825256


## 3. Classification perceptron with sigmoid and log-loss

In [4]:
sig=lambda z:1/(1+np.exp(-z))
Xc=np.array([[0,0],[0,1],[1,0],[1,1]],float); yc=np.array([0,0,0,1.])   # AND
w=np.zeros(2); b=0.
for _ in range(5000):
    yh=sig(Xc@w+b); w-=0.5*Xc.T@(yh-yc)/4; b-=0.5*np.mean(yh-yc)
print(np.round(sig(Xc@w+b),3))

[0.    0.008 0.008 0.989]


## 4. XOR is not linearly separable

In [5]:
yx=np.array([0,1,1,0.]); w=np.zeros(2); b=0.
for _ in range(5000):
    yh=sig(Xc@w+b); w-=0.5*Xc.T@(yh-yx)/4; b-=0.5*np.mean(yh-yx)
print(np.round(sig(Xc@w+b),3), "<- stuck near 0.5")

[0.5 0.5 0.5 0.5] <- stuck near 0.5


## Cambodian textbook corner (កម្មវិធីសិក្សាកម្ពុជា)
Grade 7–9 inequalities (e.g. x+y>1.5) are the school-level version of the perceptron's decision rule.

In [6]:
print(((Xc@np.array([1,1])-1.5)>0).astype(int))

[0 0 0 1]


## Exercises

**Exercise 1.** Train a perceptron for OR and verify all 4 predictions.

In [7]:
# your code here

**Exercise 2.** Extend the regression perceptron to two inputs: learn t = 3*x1 - 2*x2 + 1 from 200 random points; the weights should come out near [3, -2] and the bias near 1.

In [8]:
# your code here

## Solutions
*(Try the exercises first!)*

In [9]:
# Solution 1
yo=np.array([0,1,1,1.]); w=np.zeros(2); b=0.
for _ in range(5000):
    yh=sig(Xc@w+b); w-=0.5*Xc.T@(yh-yo)/4; b-=0.5*np.mean(yh-yo)
assert ((sig(Xc@w+b)>0.5)==yo).all()

In [10]:
# Solution 2
rng=np.random.default_rng(5); X2=rng.uniform(0,5,(200,2)); t2=3*X2[:,0]-2*X2[:,1]+1
w2=np.zeros(2); b2=0.
for _ in range(5000):
    err=X2@w2+b2-t2; w2-=0.02*X2.T@err/200; b2-=0.02*err.mean()
print(w2,b2); assert np.allclose(w2,[3,-2],atol=0.05) and abs(b2-1)<0.1

[ 3. -2.] 0.9999990960385917
